package dev.hossain.remotenotify.model

import dev.hossain.remotenotify.utils.toTitleCase
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.Locale

/**
 * Represents an alert generated by a device, such as low battery or storage.
 * Contains information about the alert type, device details, and timestamp.
 */
data class DeviceAlert(
    /** The type of alert, e.g., BATTERY, STORAGE. */
    val alertType: AlertType,
    /** The brand of the device, e.g., "Google". Defaults to `android.os.Build.BRAND`. */
    val deviceBrand: String = android.os.Build.BRAND,
    /** The model of the device, e.g., "Pixel 7". Defaults to `android.os.Build.MODEL`. */
    val deviceModel: String = android.os.Build.MODEL,
    /** The Android version of the device, e.g., "14". Defaults to `android.os.Build.VERSION.RELEASE`. */
    val androidVersion: String = android.os.Build.VERSION.RELEASE,
    /** The battery level of the device at the time of the alert, as a percentage (0-100). Null if not applicable. */
    val batteryLevel: Int? = null,
    /** The available storage space on the device in Gigabytes (GB) at the time of the alert. Null if not applicable. */
    val availableStorageGb: Double? = null,
    /** The timestamp when the alert was generated. Defaults to the current time. */
    val timestamp: LocalDateTime = LocalDateTime.now(),
) {
    /**
     * Formats the device alert information into a string representation based on the specified format type.
     *
     * @param formatType The desired format for the output string. See [FormatType].
     * @return A string representation of the device alert in the specified format.
     */
    fun format(formatType: FormatType): String =
        when (formatType) {
            FormatType.EXTENDED_TEXT -> toExtendedText()
            FormatType.HTML -> toHtml()
            FormatType.JSON -> toJson()
            FormatType.TEXT -> toText()
        }

    /**
     * Defines the available formats for representing the [DeviceAlert] information.
     */
    enum class FormatType {
        /** Provides a detailed, human-readable text format with more context. */
        EXTENDED_TEXT,

        /** Formats the alert as an HTML document, suitable for display in web views or email clients. */
        HTML,

        /** Formats the alert as a JSON string, suitable for machine processing or API communication. */
        JSON,

        /** Provides a concise, human-readable plain text format. */
        TEXT,
    }

    internal fun toJson(): String {
        val payload =
            DeviceAlertJsonPayload(
                alertType = alertType,
                deviceModel = deviceName(),
                androidVersion = androidVersion,
                batteryLevel = batteryLevel,
                availableStorageGb = availableStorageGb,
                isoDateTime = timestamp.format(DateTimeFormatter.ISO_LOCAL_DATE_TIME),
            )
        return payload.toJson()
    }

    internal fun toText(): String {
        val formatter = DateTimeFormatter.ofPattern("MMM dd, yyyy 'at' HH:mm:ss")
        val formattedTimestamp = timestamp.format(formatter)
        val alertMessage =
            when (alertType) {
                AlertType.BATTERY -> "Battery Level is at $batteryLevel%"
                AlertType.STORAGE -> "Storage Space Available: $availableStorageGb GB"
            }

        return buildString {
            append("⚠️ ${alertType.name.toTitleCase()} Alert")
            append("\n📱 ${deviceName()}")
            append("\n📍 Android $androidVersion")
            append("\n${getAlertEmoji()} $alertMessage")
            append("\n🕒 $formattedTimestamp")
        }
    }

    internal fun toExtendedText(): String {
        val formatter = DateTimeFormatter.ofPattern("EEEE, MMM dd, yyyy 'at' HH:mm:ss")
        val formattedTimestamp = timestamp.format(formatter)
        val (message, action) =
            when (alertType) {
                AlertType.BATTERY ->
                    Pair(
                        "Device battery is critically low at $batteryLevel%",
                        "Please connect your device to a charger to prevent shutdown.",
                    )
                AlertType.STORAGE ->
                    Pair(
                        "Available storage space is low ($availableStorageGb GB)",
                        "Consider removing unused apps or media files to free up space.",
                    )
            }

        return buildString {
            append("${getAlertEmoji()} Alert: ${alertType.name.toTitleCase()} Low\n\n")
            append("📱 Device: ${deviceName()}\n")
            append("📍 System: Android $androidVersion\n")
            append("ℹ️ Status: $message\n")
            append("⚡ Action: $action\n\n")
            append("🕒 Reported on: $formattedTimestamp")
        }
    }

    internal fun toHtml(): String {
        val formatter = DateTimeFormatter.ofPattern("EEEE, MMM dd, yyyy 'at' HH:mm:ss")
        val formattedTimestamp = timestamp.format(formatter)
        val (message, action) =
            when (alertType) {
                AlertType.BATTERY ->
                    Pair(
                        "Device battery is critically low at $batteryLevel%",
                        "Please connect your device to a charger to prevent shutdown.",
                    )
                AlertType.STORAGE ->
                    Pair(
                        "Available storage space is low ($availableStorageGb GB)",
                        "Consider removing unused apps or media files to free up space.",
                    )
            }

        return """
            <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
                <h2 style="color: #d32f2f;">${getAlertEmoji()} ${alertType.name.toTitleCase()} Alert</h2>
                <div style="background: #f5f5f5; padding: 15px; border-radius: 8px; margin: 15px 0;">
                    <p style="margin: 5px 0;"><strong>📱 Device:</strong> ${deviceName()}</p>
                    <p style="margin: 5px 0;"><strong>📍 System:</strong> Android $androidVersion</p>
                    <p style="margin: 5px 0;"><strong>ℹ️ Status:</strong> $message</p>
                    <p style="margin: 5px 0;"><strong>⚡ Action Required:</strong> $action</p>
                    <p style="margin: 5px 0; color: #666;"><strong>🕒 Reported on:</strong> $formattedTimestamp</p>
                </div>
                <p style="font-size: 12px; color: #666;">
                    This is an automated remote alert from your Android device monitoring system.<br/>
                    Sent by <a href="https://play.google.com/store/apps/details?id=dev.hossain.remotenotify&pcampaignid=web_share" style="color: #1976d2; text-decoration: none;">Remote Notify</a> app.
                </p>
            </div>
            """.trimIndent()
    }

    private fun deviceName(): String =
        "${deviceBrand.replaceFirstChar {
            if (it.isLowerCase()) {
                it.titlecase(
                    Locale.US,
                )
            } else {
                it.toString()
            }
        }} $deviceModel"

    private fun getAlertEmoji() =
        when (alertType) {
            AlertType.BATTERY -> "🪫"
            AlertType.STORAGE -> "💾"
        }
}

// Example usage:
fun main() {
    val batteryAlert =
        DeviceAlert(
            alertType = AlertType.BATTERY,
            deviceBrand = "Google",
            deviceModel = "Pixel 7",
            androidVersion = "Android 14",
            batteryLevel = 15,
        )

    val storageAlert =
        DeviceAlert(
            alertType = AlertType.STORAGE,
            deviceBrand = "Samsung",
            deviceModel = "Galaxy S23",
            androidVersion = "Android 13",
            availableStorageGb = 3.2,
        )

    println("Battery Alert (JSON):")
    println(batteryAlert.format(DeviceAlert.FormatType.JSON))

    println("\n----------------------------------------\n")

    println("\nStorage Alert (TEXT):")
    println(storageAlert.format(DeviceAlert.FormatType.TEXT))

    println("\n----------------------------------------\n")

    println("\nBattery Alert (TEXT):")
    println(batteryAlert.format(DeviceAlert.FormatType.TEXT))

    println("\n----------------------------------------\n")

    println("\nBattery Alert (EXTENDED_TEXT):")
    println(batteryAlert.format(DeviceAlert.FormatType.EXTENDED_TEXT))

    println("\n----------------------------------------\n")

    println("\nBattery Alert (HTML):")
    println(batteryAlert.format(DeviceAlert.FormatType.HTML))
}
