allow:
  # Google's Android development services
  - dl.google.com
  - maven.google.com
  - "*.googleapis.com"
  - "*.gstatic.com"
  - storage.googleapis.com
  
  # Firebase services
  - "*.firebase.google.com"
  - "*.firebaseapp.com"
  
  # Maven repositories
  - repo1.maven.org
  - central.maven.org
  - repo.maven.apache.org
  
  # Gradle services
  - plugins.gradle.org
  - services.gradle.org